add cnn attention & simple loss logger
RaphaelKreft/DeepLearningProject pull request #12
Opened 2024-12-18 22:00 UTC by Kristen-Z

2025-01-04 00:58 UTC, RaphaelKreft requested changes
The backbone needs a decoder for masked prediction. Please add one. You can have a look at #11 in cnn_backbone.py or ask @Ahwodafo

2025-01-04 01:14 UTC, RaphaelKreft commented on train_crl.py
> +        if self.train_iter % self.tp_cfg['val_period'] == 0:
by removing indentation this will evaluate at max 1 time at the end of an epoch but I don't think we want this? At least its not implemented like this in the repo.

2025-01-04 01:18 UTC, RaphaelKreft commented on train_crl.py
> +        return avg_eval_loss
What are your thoughts regarding avg loss vs summed loss being returned here? @Kristen-Z

2025-01-04 02:28 UTC, RaphaelKreft requested changes
also there are some changes to the logging necessary. You can look at #17 where I implemented and tested it for masked prediction training script

2025-01-04 02:28 UTC, RaphaelKreft commented on train_crl.py
> +            self.writer.add_scalar(f"Loss/{mode.capitalize()}", avg_eval_loss, epoch)
If we let eval happen based on train iterations, log via train_iterations not epoch

2025-01-04 22:53 UTC, Kristen-Z commented on train_crl.py
> +        return avg_eval_loss
I feel average loss is more standard, easy to compare, and batch size won’t skew it.

2025-01-04 23:31 UTC, Kristen-Z commented on train_crl.py
> +        if self.train_iter % self.tp_cfg['val_period'] == 0:
You're right, my bad! It should be evaluated more often. Thanks for catching that!

2025-01-05 00:25 UTC, Kristen-Z commented on train_crl.py
> +            self.writer.add_scalar(f"Loss/{mode.capitalize()}", avg_eval_loss, epoch)
I have changed this and added more logging metrics in `train_ctrl.py` .

2025-01-06 09:13 UTC, RaphaelKreft approved these changes
Lgtm, will do integration. into existing code on another Branch

2025-01-06 09:13 UTC, merged